# Generated by Django 4.2 on 2024-09-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transition',
            name='conditions',
        ),
    ]
