# Generated by Django 4.2 on 2024-09-30 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_service_base_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AlterUniqueTogether(
            name='transition',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='transition',
            name='from_state',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='to_state',
        ),
        migrations.RemoveField(
            model_name='transitionentry',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='transitionentry',
            name='from_state',
        ),
        migrations.RemoveField(
            model_name='transitionentry',
            name='to_state',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Transition',
        ),
        migrations.DeleteModel(
            name='TransitionEntry',
        ),
    ]
