# Generated by Django 4.2 on 2024-09-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_transition_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conditions', models.ManyToManyField(blank=True, to='database.condition')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_entries', to='database.state')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_entries', to='database.state')),
            ],
            options={
                'verbose_name': 'Transition Entry',
                'verbose_name_plural': 'Transition Entries',
                'db_table': 'transition_entry',
                'ordering': ['from_state', 'to_state'],
            },
        ),
    ]
