# Generated by Django 4.2 on 2024-09-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='base_url',
            field=models.CharField(max_length=255),
        ),
    ]
